"""add goals

Revision ID: 36d9786f3272
Revises: a2d4b8556061
Create Date: 2024-02-01 19:51:12.972007

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '36d9786f3272'
down_revision: Union[str, None] = 'a2d4b8556061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Номер сотрудника'),
    sa.Column('goal_name', sa.String(length=500), nullable=False, comment='Цель развития'),
    sa.Column('employee_side_plus', sa.String(length=500), nullable=False, comment='Сильные стороны'),
    sa.Column('employee_side_minus', sa.String(length=500), nullable=False, comment='Зоны развития'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    # ### end Alembic commands ###
