"""rebuild goals

Revision ID: ea24a4736af3
Revises: c57c1e74b1b3
Create Date: 2024-01-30 13:28:11.642963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea24a4736af3'
down_revision: Union[str, None] = 'c57c1e74b1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'goal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('goal_id', sa.UUID(), autoincrement=False, nullable=False, comment='Номер цели развития'))
    # ### end Alembic commands ###
