"""add_goal

Revision ID: c57c1e74b1b3
Revises: 8e68069cf1d2
Create Date: 2024-01-29 16:38:28.499615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57c1e74b1b3'
down_revision: Union[str, None] = '8e68069cf1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('goal_id', sa.UUID(as_uuid=100), nullable=False, comment='Номер цели развития'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Номер сотрудника'),
    sa.Column('goal_name', sa.String(length=500), nullable=False, comment='Цель развития'),
    sa.Column('employee_side_plus', sa.String(length=500), nullable=False, comment='Сильные стороны'),
    sa.Column('employee_side_minus', sa.String(length=500), nullable=False, comment='Зоны развития'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    # ### end Alembic commands ###
