"""init migration

Revision ID: 1ae4d3429115
Revises: 
Create Date: 2024-01-18 14:27:53.875196

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1ae4d3429115"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=64), nullable=False, comment="Имя пользователя"),
        sa.Column("family_name", sa.String(length=64), nullable=False, comment="Фамилия пользователя"),
        sa.Column("surname", sa.String(length=64), nullable=False, comment="Отчество пользователя"),
        sa.Column("position", sa.String(length=64), nullable=False, comment="Должность пользователя"),
        sa.Column(
            "role",
            postgresql.ENUM("employee", "supervisor", name="user_role"),
            server_default="employee",
            nullable=False,
            comment="Роль пользователя",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.execute("DROP TYPE user_role")
    # ### end Alembic commands ###
