"""add Team model

Revision ID: f758f905ce44
Revises: b79887e7d53d
Create Date: 2024-01-21 19:28:53.829012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f758f905ce44'
down_revision: Union[str, None] = 'b79887e7d53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Наименование команды'),
    sa.Column('leader', sa.UUID(), nullable=False, comment='Порядковый номер сотрудника в списке команды, который назначен руководителем команды'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leader'], ['users.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('team_id', sa.UUID(), nullable=False, comment='Порядковый номер в списке команды'))
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               comment='Имя сотрудника',
               existing_comment='Имя пользователя',
               existing_nullable=False)
    op.alter_column('users', 'family_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               comment='Фамилия сотрудника',
               existing_comment='Фамилия пользователя',
               existing_nullable=False)
    op.alter_column('users', 'surname',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               comment='Наименование должности / специальности в команде',
               existing_comment='Отчество пользователя',
               existing_nullable=False)
    op.alter_column('users', 'position',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               comment='Должность сотрудника',
               existing_comment='Должность пользователя',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               comment='Роль сотрудника',
               existing_comment='Роль пользователя',
               existing_nullable=False)
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               comment='Роль пользователя',
               existing_comment='Роль сотрудника',
               existing_nullable=False)
    op.alter_column('users', 'position',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               comment='Должность пользователя',
               existing_comment='Должность сотрудника',
               existing_nullable=False)
    op.alter_column('users', 'surname',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               comment='Отчество пользователя',
               existing_comment='Наименование должности / специальности в команде',
               existing_nullable=False)
    op.alter_column('users', 'family_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               comment='Фамилия пользователя',
               existing_comment='Фамилия сотрудника',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               comment='Имя пользователя',
               existing_comment='Имя сотрудника',
               existing_nullable=False)
    op.drop_column('users', 'team_id')
    op.drop_table('teams')
    # ### end Alembic commands ###
