"""add Task Idp Status Comment model

Revision ID: e6d0d460e7d5
Revises: 8e68069cf1d2
Create Date: 2024-01-29 17:45:46.705337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d0d460e7d5'
down_revision: Union[str, None] = '8e68069cf1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('slug', sa.String(length=20), nullable=False, comment='Описание на англйском для фронта'),
    sa.Column('description', sa.String(length=20), nullable=False, comment='Описание статуса задачи'),
    sa.Column('weight', sa.Integer(), nullable=False, comment='Вес статуса для сортировки'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idp',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Статус выполнения задачи'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Начало ИПР'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='Окончание ИПР'),
    sa.Column('year', sa.Integer(), nullable=False, comment='Год ИПР'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='idp_users_fkey', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Наименование задачи'),
    sa.Column('description', sa.String(length=1000), nullable=False, comment='Подробности задачи'),
    sa.Column('task_type', sa.String(length=20), nullable=False, comment='Тип задачи'),
    sa.Column('start_time', sa.Date(), nullable=False, comment='Дата начала'),
    sa.Column('end_time', sa.Date(), nullable=False, comment='Дата окончания'),
    sa.Column('importance', sa.String(length=10), nullable=False, comment='Значимость задачи'),
    sa.Column('idp_id', sa.UUID(), nullable=False, comment='Идентификатор ИПР задачи'),
    sa.Column('status_id', sa.UUID(), nullable=False, comment='Статус выполнения задачи'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idp_id'], ['idp.id'], name='task_idp_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name='task_status', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Комментарий от пользователя'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Комментарий задачи'),
    sa.Column('text', sa.String(length=1000), nullable=False, comment='Текст комментария'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_comment', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_comment', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('tasks')
    op.drop_table('idp')
    op.drop_table('status')
    # ### end Alembic commands ###
