"""add users contacts

Revision ID: ae3466a44ea4
Revises: 36d9786f3272
Create Date: 2024-02-04 21:17:01.773091

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae3466a44ea4'
down_revision: Union[str, None] = '36d9786f3272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
                  sa.Column('email', sa.String(length=100), nullable=True, comment='Электронная почта пользователя'))
    op.add_column('users', sa.Column('phone_number', sa.String(length=100), nullable=True,
                                     comment='Номер телефона пользователя'))
    op.add_column('users', sa.Column('telegram', sa.String(length=100), nullable=True, comment='Telegram пользователя'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'email')
    op.create_table('goals',
                    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='Номер сотрудника'),
                    sa.Column('goal_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False,
                              comment='Цель развития'),
                    sa.Column('employee_side_plus', sa.VARCHAR(length=500), autoincrement=False, nullable=False,
                              comment='Сильные стороны'),
                    sa.Column('employee_side_minus', sa.VARCHAR(length=500), autoincrement=False, nullable=False,
                              comment='Зоны развития'),
                    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'),
                              autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_fkey', onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='goals_pkey')
                    )
    # ### end Alembic commands ###
