"""add avatar field to User model

Revision ID: a2d4b8556061
Revises: e6d0d460e7d5
Create Date: 2024-01-30 20:22:00.970153

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a2d4b8556061'
down_revision: Union[str, None] = 'e6d0d460e7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idp', 'user_id',
                    existing_type=sa.UUID(),
                    comment='ID пользователя',
                    existing_comment='Статус выполнения задачи',
                    existing_nullable=False)
    op.add_column('users', sa.Column('avatar', sa.Text(), nullable=True,
                                     comment='Аватар пользователя'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.alter_column('idp', 'user_id',
                    existing_type=sa.UUID(),
                    comment='Статус выполнения задачи',
                    existing_comment='ID пользователя',
                    existing_nullable=False)
    # ### end Alembic commands ###
