version: '3.8'

services:

  alfa-bank-pdp-backend-nginx:
    ports:
      - ${FRONTEND_PORT:-80}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/configs:/etc/nginx/conf.d:rw

  alfa-bank-pdp-backend-db:
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  alfa-bank-pdp-backend-redis:
    ports:
      - ${REDIS_PORT:-6379}:6379

  alfa-bank-pdp-backend-api:
    command: poetry run uvicorn --factory app.main:main --host 0.0.0.0 --port ${BACKEND_PORT:-8080} --reload
    volumes:
      - ../src/app:/opt/app
      - ../src/database:/opt/database
    env_file:
      - ../src/.env

  alfa-bank-pdp-backend-migration:
    volumes:
      - ../src/app:/opt/app
      - ../src/database:/opt/database
    env_file:
      - ../src/.env

networks:
  alfa-bank-pdp-backend-network:
    name: alfa-bank-pdp-backend-network
    external: true

volumes:
  db_data:
